-- MySQL Script generated by MySQL Workbench
-- mar 26 abr 2022 17:38:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UNILINK
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `UNILINK` ;

-- -----------------------------------------------------
-- Schema UNILINK
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UNILINK` ;
USE `UNILINK` ;

-- -----------------------------------------------------
-- Table `UNILINK`.`Eskatzailea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNILINK`.`Eskatzailea` ;

CREATE TABLE IF NOT EXISTS `UNILINK`.`Eskatzailea` (
  `idEskatzailea` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `pasahitza` VARCHAR(45) NOT NULL,
  `izenAbizenak` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tituluak` VARCHAR(250) NULL,
  `bizilekua` VARCHAR(250) NULL,
  `hizkuntzak` VARCHAR(250) NULL,
  `gaitasunak` VARCHAR(250) NULL,
  `mota` VARCHAR(45) NULL,
  PRIMARY KEY (`idEskatzailea`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNILINK`.`Eskaintzailea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNILINK`.`Eskaintzailea` ;

CREATE TABLE IF NOT EXISTS `UNILINK`.`Eskaintzailea` (
  `idEskaintzailea` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `pasahitza` VARCHAR(45) NOT NULL,
  `izena` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `saila` VARCHAR(45) NOT NULL,
  `kokalekua` VARCHAR(250) NULL,
  `lanEsparrua` VARCHAR(45) NULL,
  `laburpena` VARCHAR(45) NULL,
  `enpresaIzena` VARCHAR(45) NULL,
  `mota` VARCHAR(45) NULL,
  PRIMARY KEY (`idEskaintzailea`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNILINK`.`Eskaintza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNILINK`.`Eskaintza` ;

CREATE TABLE IF NOT EXISTS `UNILINK`.`Eskaintza` (
  `idEskaintza` INT NOT NULL AUTO_INCREMENT,
  `azalpena` VARCHAR(300) NOT NULL,
  `materiala` VARCHAR(45) NULL,
  `eskakizunak` VARCHAR(150) NULL,
  `graduak` VARCHAR(250) NOT NULL,
  `ordutegia` VARCHAR(45) NULL,
  `orduak` INT NULL,
  `iraupena` VARCHAR(45) NULL,
  `prezioa` FLOAT NULL,
  `lekua` VARCHAR(250) NULL,
  `oporrak` VARCHAR(45) NULL,
  `soldata` FLOAT NULL,
  `deialdia` INT NULL,
  `izenburua` VARCHAR(45) NULL,
  `saila` VARCHAR(45) NULL,
  `tutorea` VARCHAR(45) NULL,
  `Eskaintzailea_idEskaintzailea` INT NOT NULL,
  `eskaintzaEgoera` INT NULL,
  PRIMARY KEY (`idEskaintza`),
  INDEX `fk_Eskaintza_Eskaintzailea1_idx` (`Eskaintzailea_idEskaintzailea` ASC) VISIBLE,
  CONSTRAINT `fk_Eskaintza_Eskaintzailea1`
    FOREIGN KEY (`Eskaintzailea_idEskaintzailea`)
    REFERENCES `UNILINK`.`Eskaintzailea` (`idEskaintzailea`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNILINK`.`Erlazioa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNILINK`.`Erlazioa` ;

CREATE TABLE IF NOT EXISTS `UNILINK`.`Erlazioa` (
  `idErlazioa` INT NOT NULL AUTO_INCREMENT,
  `eskariaEgoera` INT NULL,
  `Eskatzailea_idEskatzailea` INT NOT NULL,
  `Eskaintza_idEskaintza` INT NOT NULL,
  PRIMARY KEY (`idErlazioa`),
  INDEX `fk_Erlazioa_Eskatzailea1_idx` (`Eskatzailea_idEskatzailea` ASC) VISIBLE,
  INDEX `fk_Erlazioa_Eskaintza1_idx` (`Eskaintza_idEskaintza` ASC) VISIBLE,
  CONSTRAINT `fk_Erlazioa_Eskatzailea1`
    FOREIGN KEY (`Eskatzailea_idEskatzailea`)
    REFERENCES `UNILINK`.`Eskatzailea` (`idEskatzailea`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Erlazioa_Eskaintza1`
    FOREIGN KEY (`Eskaintza_idEskaintza`)
    REFERENCES `UNILINK`.`Eskaintza` (`idEskaintza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNILINK`.`Komentarioak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNILINK`.`Komentarioak` ;

CREATE TABLE IF NOT EXISTS `UNILINK`.`Komentarioak` (
  `idKomentarioak` INT NOT NULL AUTO_INCREMENT,
  `testua` VARCHAR(250) NOT NULL,
  `Eskaintza_idEskaintza` INT NOT NULL,
  `Eskatzailea_idEskatzailea` INT NOT NULL,
  `Komentarioak_idKomentarioak` INT NULL,
  PRIMARY KEY (`idKomentarioak`),
  INDEX `fk_Komentarioak_Eskaintza1_idx` (`Eskaintza_idEskaintza` ASC) VISIBLE,
  INDEX `fk_Komentarioak_Eskatzailea1_idx` (`Eskatzailea_idEskatzailea` ASC) VISIBLE,
  INDEX `fk_Komentarioak_Komentarioak1_idx` (`Komentarioak_idKomentarioak` ASC) VISIBLE,
  CONSTRAINT `fk_Komentarioak_Eskaintza1`
    FOREIGN KEY (`Eskaintza_idEskaintza`)
    REFERENCES `UNILINK`.`Eskaintza` (`idEskaintza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Komentarioak_Eskatzailea1`
    FOREIGN KEY (`Eskatzailea_idEskatzailea`)
    REFERENCES `UNILINK`.`Eskatzailea` (`idEskatzailea`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Komentarioak_Komentarioak1`
    FOREIGN KEY (`Komentarioak_idKomentarioak`)
    REFERENCES `UNILINK`.`Komentarioak` (`idKomentarioak`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNILINK`.`Erabiltzailea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNILINK`.`Erabiltzailea` ;

CREATE TABLE IF NOT EXISTS `UNILINK`.`Erabiltzailea` (
  `idErabiltzailea` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `pasahitza` VARCHAR(45) NOT NULL,
  `mota` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idErabiltzailea`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
